baseURL = "/"
languageCode = "en-us"
title = "Quants & Quills"
theme = "kube"
description = "Quants and Quills is an organisation based in Brisbane, Australia dedicated to exploring the intersection of technology and storytelling."
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "newpixcom" # add your company name
  github = "" # add your github profile name
  twitter = "" # add your twitter profile
  email = "myemail@myaddress.xxx"

[[menu.main]]
    name = "Docs"
    weight = -100
    url = "/docs/"
[[menu.main]]
    name = "Blog"
    weight = -100
    url = "/blog/"
[[menu.main]]
    name = "Faq"
    weight = -100
    url = "/faq/"
