baseURL = "/"
languageCode = "en-us"
title = "Quants & Quills"
theme = "kube"
description = "Quants and Quills is an organisation based in Brisbane, Australia dedicated to exploring the intersection of technology and storytelling."
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "quantsandquills" # add your company name
  twitter = "hackshackersbne" # add your twitter profile

[[menu.main]]
    name = "Events"
    weight = -100
    url = "/events/"
[[menu.main]]
    name = "Faq"
    weight = -90
    url = "/faq/"
